# This manifest holds the information the app needs to run on Nextmv.

# Type and runtime specify the language and environment of the app.
type: go
runtime: ghcr.io/nextmv-io/runtime/default:latest

# Directives to build a Go binary from the app.
build:
  command: go build -o main .
  # Use Linux ARM64 as the target for Nextmv Cloud.
  environment:
    GOOS: linux
    GOARCH: arm64

# List all files/directories that should be included in the app. Globbing
# (e.g.: configs/*.json) is supported.
files:
  - main

# Application configurations.
configuration:
  # Define the content format of the app, one of: json, multi-file.
  content:
    format: "multi-file" # Read and write files from disk.
    # Configuration of the multi-file format.
    multi-file:
      input:
        path: inputs # Directory where the app will read input files from.
      output:
        solutions: outputs/solutions # Directory where the app will write solution files to.
        metrics: outputs/metrics/metrics.json # Path where the app will write metrics to.
  # Define the options (parameters) of the app.
  options:
    items:
      - name: details
        option_type: bool
        default: true
        description: Print details to logs. Default true.
        required: false
        ui:
          display_name: Details
