site_name: Nextmv Python SDKs
site_description: Documentation for the Nextmv Python SDKs
repo_url: https://github.com/nextmv-io/nextmv-py
repo_name: nextmv-io/nextmv-py
site_author: Nextmv

nav:
  - Home: index.md
  - nextmv:
      - 👋 Overview & installation: nextmv/index.md
      - ✏️ Modeling:
          - Overview: nextmv/modeling/index.md
          - Options: nextmv/modeling/options.md
          - Input: nextmv/modeling/input.md
          - Logging: nextmv/modeling/logging.md
          - Output: nextmv/modeling/output.md
          - Model: nextmv/modeling/model.md
          - Reference:
              - base_model.py: nextmv/modeling/reference/base_model.md
              - input.py: nextmv/modeling/reference/input.md
              - logger.py: nextmv/modeling/reference/logger.md
              - manifest.py: nextmv/modeling/reference/manifest.md
              - model.py: nextmv/modeling/reference/model.md
              - options.py: nextmv/modeling/reference/options.md
              - output.py: nextmv/modeling/reference/output.md
              - polling.py: nextmv/modeling/reference/polling.md
              - run.py: nextmv/modeling/reference/run.md
              - safe.py: nextmv/modeling/reference/safe.md
              - status.py: nextmv/modeling/reference/status.md
      - 💻 Local:
          - Overview: nextmv/local/index.md
          - Get started - new app: nextmv/local/get-started-new-app.md
          - Get started - existing app: nextmv/local/get-started-existing-app.md
          - Run an app: nextmv/local/runs.md
          - Sync to Cloud: nextmv/local/sync.md
          - Visualize run assets: nextmv/local/visuals.md
          - Reference:
              - application.py: nextmv/local/reference/application.md
              - executor.py: nextmv/local/reference/executor.md
              - geojson_handler.py: nextmv/local/reference/geojson_handler.md
              - local.py: nextmv/local/reference/local.md
              - plotly_handler.py: nextmv/local/reference/plotly_handler.md
              - runner.py: nextmv/local/reference/runner.md
      - ☁️ Cloud:
          - Overview: nextmv/cloud/index.md
          - Managing an app: nextmv/cloud/manage.md
          - Push to an app: nextmv/cloud/push.md
          - Run an app: nextmv/cloud/runs.md
          - Versions: nextmv/cloud/versions.md
          - Instances: nextmv/cloud/instances.md
          - Track runs: nextmv/cloud/external-runs.md
          - Secrets: nextmv/cloud/secrets.md
          - Large payloads: nextmv/cloud/large-payloads.md
          - Queuing & prioritization: nextmv/cloud/queuing.md
          - Execution classes: nextmv/cloud/execution-classes.md
          - Scenario tests: nextmv/cloud/scenario-tests.md
          - Batch experiments: nextmv/cloud/batch-experiments.md
          - Acceptance tests: nextmv/cloud/acceptance-tests.md
          - Input sets: nextmv/cloud/input-sets.md
          - Reference:
              - acceptance_test.py: nextmv/cloud/reference/acceptance_test.md
              - account.py: nextmv/cloud/reference/account.md
              - application.py: nextmv/cloud/reference/application.md
              - batch_experiment.py: nextmv/cloud/reference/batch_experiment.md
              - client.py: nextmv/cloud/reference/client.md
              - ensemble.py: nextmv/cloud/reference/ensemble.md
              - input_set.py: nextmv/cloud/reference/input_set.md
              - instance.py: nextmv/cloud/reference/instance.md
              - scenario.py: nextmv/cloud/reference/scenario.md
              - secrets.py: nextmv/cloud/reference/secrets.md
              - url.py: nextmv/cloud/reference/url.md
              - version.py: nextmv/cloud/reference/version.md
  - nextmv-gurobipy:
      - 👋 Overview & installation: nextmv-gurobipy/index.md
      - 📓 Tutorials:
          - Options: nextmv-gurobipy/tutorials/options.md
          - Model: nextmv-gurobipy/tutorials/model.md
          - Statistics: nextmv-gurobipy/tutorials/statistics.md
          - Solution: nextmv-gurobipy/tutorials/solution.md
      - ⚙️ Reference:
          - model.py: nextmv-gurobipy/reference/model.md
          - options.py: nextmv-gurobipy/reference/options.md
          - solution.py: nextmv-gurobipy/reference/solution.md
          - statistics.py: nextmv-gurobipy/reference/statistics.md
  - nextmv-scikit-learn:
      - 👋 Overview & installation: nextmv-scikit-learn/index.md
      - 📓 Tutorials:
          - Options: nextmv-scikit-learn/tutorials/options.md
          - Model: nextmv-scikit-learn/tutorials/model.md
          - Statistics: nextmv-scikit-learn/tutorials/statistics.md
          - Solution: nextmv-scikit-learn/tutorials/solution.md
      - ⚙️ Reference:
          - dummy:
              - model.py: nextmv-scikit-learn/reference/dummy/model.md
              - options.py: nextmv-scikit-learn/reference/dummy/options.md
              - solution.py: nextmv-scikit-learn/reference/dummy/solution.md
              - statistics.py: nextmv-scikit-learn/reference/dummy/statistics.md
          - ensemble:
              - model.py: nextmv-scikit-learn/reference/ensemble/model.md
              - options.py: nextmv-scikit-learn/reference/ensemble/options.md
              - solution.py: nextmv-scikit-learn/reference/ensemble/solution.md
              - statistics.py: nextmv-scikit-learn/reference/ensemble/statistics.md
          - linear_model:
              - model.py: nextmv-scikit-learn/reference/linear_model/model.md
              - options.py: nextmv-scikit-learn/reference/linear_model/options.md
              - solution.py: nextmv-scikit-learn/reference/linear_model/solution.md
              - statistics.py: nextmv-scikit-learn/reference/linear_model/statistics.md
          - neural_network:
              - model.py: nextmv-scikit-learn/reference/neural_network/model.md
              - options.py: nextmv-scikit-learn/reference/neural_network/options.md
              - solution.py: nextmv-scikit-learn/reference/neural_network/solution.md
              - statistics.py: nextmv-scikit-learn/reference/neural_network/statistics.md
          - tree:
              - model.py: nextmv-scikit-learn/reference/tree/model.md
              - options.py: nextmv-scikit-learn/reference/tree/options.md
              - solution.py: nextmv-scikit-learn/reference/tree/solution.md
              - statistics.py: nextmv-scikit-learn/reference/tree/statistics.md
          - ndarray.py: nextmv-scikit-learn/reference/ndarray.md
theme:
  name: material
  logo: images/logo-180.png
  favicon: images/nextmv-favicon.svg
  font:
    text: L10-Web
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.collapse
    - navigation.sections
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - search.highlight
    - search.share
    - toc.follow
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: cyan
      accent: indigo
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            backlinks: tree
            show_source: true
            heading_level: 2
            parameter_headings: true
            show_root_heading: true
            show_root_toc_entry: false
            show_root_full_path: false
            show_root_members_full_path: false
            show_object_full_path: false
            group_by_category: false
            show_category_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            inherited_members: true
            members_order: alphabetical
            show_submodules: true
            show_labels: true
            docstring_style: numpy
            docstring_section_style: spacy
            docstring_options:
              ignore_init_summary: false
            merge_init_into_class: true
            relative_crossrefs: true
            show_if_no_docstring: true
            show_docstring_attributes: true
            show_docstring_functions: true
            show_docstring_classes: true
            show_docstring_modules: true
            show_docstring_description: true
            show_docstring_examples: true
            show_docstring_other_parameters: true
            show_docstring_parameters: true
            show_docstring_raises: true
            show_docstring_receives: true
            show_docstring_returns: true
            show_docstring_warns: true
            show_docstring_yields: true
            show_signature: true
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            filters:
              - "!^_"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: 4
  - attr_list
  - def_list
  - tables

extra:
  generator: false
