import os
import platform
import shutil
import subprocess
import tempfile
import unittest

from nextmv.cloud.package import (
    _get_shell_command_elements,
    _parse_direct_requirements,
    _parse_lockfile,
    package,
)
from nextmv.manifest import Manifest, ManifestType

# A representative `uv pip compile` lockfile: an autogenerated header, pinned
# `name==version` lines with indented `# via` annotations, and a trailing local
# path requirement (a self-referencing `../../` dependency).
_LOCKFILE = """\
# This file was autogenerated by uv via the following command:
#    uv pip compile requirements.txt
nextmv==1.10.1
    # via nextpipe
../../
    # via -r requirements.txt
numpy==2.4.6
    # via folium
"""


class TestParseLockfile(unittest.TestCase):
    def test_parse_lockfile_keeps_only_pinned(self):
        packages = _parse_lockfile(_LOCKFILE)
        self.assertEqual(
            packages,
            [
                {"name": "nextmv", "version": "1.10.1"},
                {"name": "numpy", "version": "2.4.6"},
            ],
        )

    def test_parse_direct_requirements_captures_local_path(self):
        # Regression test: the `../../` local path dep must not be silently
        # dropped just because it is not a `name==version` line.
        self.assertEqual(_parse_direct_requirements(_LOCKFILE), ["../../"])

    def test_parse_direct_requirements_captures_direct_and_vcs(self):
        lockfile = (
            "# header\n"
            "requests==2.32.3\n"
            "    # via -r requirements.txt\n"
            "nextpipe @ file:///abs/path\n"
            "git+https://example.com/pkg.git\n"
        )
        self.assertEqual(
            _parse_direct_requirements(lockfile),
            ["nextpipe @ file:///abs/path", "git+https://example.com/pkg.git"],
        )

    def test_parse_direct_requirements_empty_when_all_pinned(self):
        lockfile = "# header\nrequests==2.32.3\n    # via foo\nnumpy==2.4.6\n"
        self.assertEqual(_parse_direct_requirements(lockfile), [])


class TestPackageOneFile(unittest.TestCase):
    def setUp(self):
        self.app_dir = tempfile.mkdtemp()
        self.manifest = Manifest(type=ManifestType.PYTHON, files=["main.py"], python=None)
        with open(os.path.join(self.app_dir, "main.py"), "w") as f:
            f.write("print('Hello, World!')")

    def tearDown(self):
        shutil.rmtree(self.app_dir)

    def test_package_creates_tarball(self):
        tar_file, output_dir = package(self.app_dir, self.manifest, verbose=False)
        self.assertTrue(os.path.isfile(tar_file))
        self.assertTrue(os.path.isdir(output_dir))

    def test_package_missing_files(self):
        self.manifest.files.append("missing_file.py")
        with self.assertRaises(Exception) as context:
            package(self.app_dir, self.manifest, verbose=False)
        self.assertIn("could not find files listed in manifest", str(context.exception))

    def test_package_mandatory_files(self):
        self.manifest.type = ManifestType.GO
        with self.assertRaises(Exception) as context:
            package(self.app_dir, self.manifest, verbose=False)
        self.assertIn("missing mandatory files", str(context.exception))


class TestPackageDir(unittest.TestCase):
    def setUp(self):
        self.app_dir = tempfile.mkdtemp()
        self.manifest = Manifest(type=ManifestType.PYTHON, files=["main.py", "app/"], python=None)
        with open(os.path.join(self.app_dir, "main.py"), "w") as f:
            f.write("print('Hello, World!')")

        os.makedirs(os.path.join(self.app_dir, "app"))
        with open(os.path.join(self.app_dir, "app", "main.py"), "w") as f:
            f.write("print('Hello, World!')")

    def tearDown(self):
        shutil.rmtree(self.app_dir)

    def test_package_creates_tarball(self):
        tar_file, output_dir = package(self.app_dir, self.manifest, verbose=False)
        self.assertTrue(os.path.isfile(tar_file))
        self.assertTrue(os.path.isdir(output_dir))

        with tempfile.TemporaryDirectory() as tmpdir:
            shutil.unpack_archive(tar_file, tmpdir)
            self.assertTrue(os.path.isfile(os.path.join(tmpdir, "main.py")))
            self.assertTrue(os.path.isdir(os.path.join(tmpdir, "app")))
            self.assertTrue(os.path.isfile(os.path.join(tmpdir, "app", "main.py")))

    def test_package_missing_files(self):
        self.manifest.files.append("missing_file.py")
        with self.assertRaises(Exception) as context:
            package(self.app_dir, self.manifest, verbose=False)
        self.assertIn("could not find files listed in manifest", str(context.exception))

    def test_package_mandatory_files(self):
        self.manifest.type = ManifestType.GO
        with self.assertRaises(Exception) as context:
            package(self.app_dir, self.manifest, verbose=False)
        self.assertIn("missing mandatory files", str(context.exception))

    def test_get_shell_command_elements(self):
        if platform.system() == "Windows":
            command = _get_shell_command_elements("echo Hello World")
            subprocess.run(command, check=True)
        else:
            command = _get_shell_command_elements("echo 'Hello World'")
            subprocess.run(command, check=True)
