name: publish-notify
run-name: Publish and notify by @${{ github.actor }} from ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      RELEASE_NEEDED:
        description: "Whether a release is needed"
        required: true
        type: string
      SHOULD_NOTIFY_SLACK:
        description: "Whether to notify Slack"
        required: true
        type: string
      VERSION:
        description: "The version being released"
        required: true
        type: string
      PACKAGE_NAME:
        description: "The package name for notifications"
        required: true
        type: string

jobs:
  # Unfortunately, PyPI publishing does not support reusable workflows from
  # other repos, so we must publish here.
  publish:
    if: ${{ inputs.RELEASE_NEEDED == 'true' }}
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ inputs.PACKAGE_NAME }}
    permissions:
      id-token: write # This is required for trusted publishing to PyPI
    steps:
      - name: git clone ${{ github.ref_name }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: set up Python
        uses: actions/setup-python@v5

      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install build hatch

      - name: python - build binary wheel and source tarball
        run: python -m build

      - name: python - publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./dist

  notify:
    needs: [publish]
    if: ${{ inputs.RELEASE_NEEDED == 'true' && inputs.SHOULD_NOTIFY_SLACK == 'true' }}
    uses: nextmv-io/release/.github/workflows/notify-slack.yml@develop
    with:
      PACKAGE_NAME: ${{ inputs.PACKAGE_NAME }}
      VERSION: ${{ inputs.VERSION }}
      REPOSITORY: nextmv-py
    secrets: inherit
