name: python lint
on:
  push:
    branches: [develop]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
permissions:
  contents: read
jobs:
  python-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        package: ["nextmv", "nextmv-gurobipy", "nextmv-scikit-learn"]
    steps:
      - name: git clone
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
        with:
          version: "0.9.29"
          python-version: ${{ matrix.python-version }}

      - name: install the project
        run: uv sync --locked --dev
        working-directory: ./${{ matrix.package }}

      - name: lint with ruff
        run: uv run ruff check --output-format=github .
        working-directory: ./${{ matrix.package }}
