name: python lint
on: [push]
jobs:
  python-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        package: ["nextmv", "nextmv-gurobipy", "nextmv-scikit-learn"]
    steps:
      - name: git clone
        uses: actions/checkout@v6

      - name: install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.29"
          python-version: ${{ matrix.python-version }}

      - name: install the project
        run: uv sync --locked --dev
        working-directory: ./${{ matrix.package }}

      - name: lint with ruff
        run: uv run ruff check --output-format=github .
        working-directory: ./${{ matrix.package }}
