name: python test
on: [push]
jobs:
  python-test:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        platform: [ubuntu-latest, windows-latest, macos-latest, macos-13]
        package: ["nextmv", "nextmv-gurobipy", "nextmv-scikit-learn"]
    steps:
      - name: git clone
        uses: actions/checkout@v4

      - name: set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
        working-directory: ./${{ matrix.package }}

      - name: handle nextmv dependency
        if: ${{ matrix.package != 'nextmv' }}
        run: |
          pip uninstall -y nextmv
          pip install -e ../nextmv
        working-directory: ./${{ matrix.package }}

      - name: unit tests
        run: python -m unittest
        working-directory: ./${{ matrix.package }}
