name: release
run-name: Release by @${{ github.actor }} from ${{ github.ref_name }}

on: [push]

permissions:
  contents: read

jobs:
  # >>> 'nextmv' package jobs.
  release-nextmv:
    if: ${{ github.ref_type == 'branch' }}
    uses: nextmv-io/release/.github/workflows/release.yml@develop
    permissions:
      contents: write
      pull-requests: write
    with:
      BRANCH: ${{ github.ref_name }}
      REPOSITORY: nextmv-py
      LANGUAGE: python
      PACKAGE_NAME: nextmv
      PACKAGE_LOCATION: ./nextmv
      VERSION_FILE: __about__.py
      VERSION_PREFIX: nextmv-
    secrets: inherit

  release-binaries:
    name: Release ${{ matrix.os }}-${{ matrix.arch }} binaries
    needs: [release-nextmv]
    if: ${{ needs.release-nextmv.outputs.RELEASE_NEEDED == 'true' }}
    permissions:
      contents: write # This is required for uploading assets to GitHub releases
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: linux
            arch: x64
            runner: ubuntu-latest
            ext: ""
          - os: linux
            arch: arm64
            runner: ubuntu-24.04-arm
            ext: ""
          - os: macos
            arch: x64
            runner: macos-15-intel
            ext: ""
          - os: macos
            arch: arm64
            runner: macos-latest
            ext: ""
          - os: windows
            arch: x64
            runner: windows-latest
            ext: ".exe"

    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: setup Python
        uses: actions/setup-python@v6

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller uv
          pip install .
        working-directory: nextmv/

      - name: build binary with PyInstaller
        shell: bash
        # Binary will be located at nextmv/dist/nextmv (or nextmv/dist/nextmv.exe on Windows)
        run: ./.github/scripts/build-single-binary.sh

      - name: rename binary for distribution
        shell: bash
        run: |
          mv dist/nextmv${{ matrix.ext }} dist/nextmv-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}
        working-directory: nextmv/

      - name: determine exact version being released
        shell: bash
        run: |
          VERSION="nextmv-$(cat nextmv/nextmv/__about__.py | grep __version__ | cut -d '"' -f 2)"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION"

      - name: attach binary to GitHub release
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload $VERSION dist/nextmv-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }} --clobber
        working-directory: nextmv/

  # Unfortunately, PyPI publishing does not support reusable workflows, so we
  # must publish here and do copy-pasting below as well. Sorry.
  publish-nextmv:
    needs: [release-nextmv, release-binaries]
    if: ${{ needs.release-nextmv.outputs.RELEASE_NEEDED == 'true' }}
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/nextmv
    permissions:
      id-token: write # This is required for trusted publishing to PyPI
    steps:
      - name: git clone ${{ github.ref_name }}
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}

      - name: set up Python
        uses: actions/setup-python@v6

      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install build hatch

      - name: python - build binary wheel and source tarball
        run: python -m build
        working-directory: ./nextmv

      - name: python - publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./nextmv/dist

  notify-nextmv:
    needs: [release-nextmv, publish-nextmv]
    if: ${{ needs.release-nextmv.outputs.RELEASE_NEEDED == 'true' && needs.release-nextmv.outputs.SHOULD_NOTIFY_SLACK == 'true' }}
    uses: nextmv-io/release/.github/workflows/notify-slack.yml@develop
    with:
      PACKAGE_NAME: nextmv
      VERSION: ${{ needs.release-nextmv.outputs.VERSION }}
      REPOSITORY: nextmv-py
    secrets: inherit

  # >>> 'nextmv-gurobipy' package jobs.
  release-nextmv-gurobipy:
    if: ${{ github.ref_type == 'branch' }}
    uses: nextmv-io/release/.github/workflows/release.yml@develop
    permissions:
      contents: write
      pull-requests: write
    with:
      BRANCH: ${{ github.ref_name }}
      REPOSITORY: nextmv-py
      LANGUAGE: python
      PACKAGE_NAME: nextmv_gurobipy
      PACKAGE_LOCATION: ./nextmv-gurobipy
      VERSION_FILE: __about__.py
      VERSION_PREFIX: nextmv-gurobipy-
    secrets: inherit

  publish-nextmv-gurobipy:
    needs: [release-nextmv-gurobipy]
    if: ${{ needs.release-nextmv-gurobipy.outputs.RELEASE_NEEDED == 'true' }}
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/nextmv-gurobipy
    permissions:
      id-token: write # This is required for trusted publishing to PyPI
    steps:
      - name: git clone ${{ github.ref_name }}
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}

      - name: set up Python
        uses: actions/setup-python@v6

      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install build hatch

      - name: python - build binary wheel and source tarball
        run: python -m build
        working-directory: ./nextmv-gurobipy

      - name: python - publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./nextmv-gurobipy/dist

  notify-nextmv-gurobipy:
    needs: [release-nextmv-gurobipy, publish-nextmv-gurobipy]
    if: ${{ needs.release-nextmv-gurobipy.outputs.RELEASE_NEEDED == 'true' && needs.release-nextmv-gurobipy.outputs.SHOULD_NOTIFY_SLACK == 'true' }}
    uses: nextmv-io/release/.github/workflows/notify-slack.yml@develop
    with:
      PACKAGE_NAME: nextmv_gurobipy
      VERSION: ${{ needs.release-nextmv-gurobipy.outputs.VERSION }}
      REPOSITORY: nextmv-py
    secrets: inherit

  # >>> 'nextmv-scikit-learn' package jobs.
  release-nextmv-scikit-learn:
    if: ${{ github.ref_type == 'branch' }}
    uses: nextmv-io/release/.github/workflows/release.yml@develop
    permissions:
      contents: write
      pull-requests: write
    with:
      BRANCH: ${{ github.ref_name }}
      REPOSITORY: nextmv-py
      LANGUAGE: python
      PACKAGE_NAME: nextmv_sklearn
      PACKAGE_LOCATION: ./nextmv-scikit-learn
      VERSION_FILE: __about__.py
      VERSION_PREFIX: nextmv-scikit-learn-
    secrets: inherit

  publish-nextmv-scikit-learn:
    needs: [release-nextmv-scikit-learn]
    if: ${{ needs.release-nextmv-scikit-learn.outputs.RELEASE_NEEDED == 'true' }}
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/nextmv-scikit-learn
    permissions:
      id-token: write # This is required for trusted publishing to PyPI
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install build hatch

      - name: Build package
        run: python -m build
        working-directory: ./nextmv-scikit-learn

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./nextmv-scikit-learn/dist

  notify-nextmv-scikit-learn:
    needs: [release-nextmv-scikit-learn, publish-nextmv-scikit-learn]
    if: ${{ needs.release-nextmv-scikit-learn.outputs.RELEASE_NEEDED == 'true' && needs.release-nextmv-scikit-learn.outputs.SHOULD_NOTIFY_SLACK == 'true' }}
    uses: nextmv-io/release/.github/workflows/notify-slack.yml@develop
    with:
      PACKAGE_NAME: nextmv_sklearn
      VERSION: ${{ needs.release-nextmv-scikit-learn.outputs.VERSION }}
      REPOSITORY: nextmv-py
    secrets: inherit
