name: release
run-name: Release by @${{ github.actor }} from ${{ github.ref_name }}

on:
  push:
    branches:
      - "*"

jobs:
  release-nextmv:
    uses: nextmv-io/release/.github/workflows/release.yml@develop
    with:
      BRANCH: ${{ github.ref_name }}
      REPOSITORY: nextmv-py
      LANGUAGE: python
      PACKAGE_NAME: nextmv
      PACKAGE_LOCATION: ./nextmv
      VERSION_FILE: __about__.py
    secrets: inherit

  publish-notify-nextmv:
    needs: [release-nextmv]
    if: ${{ needs.release-nextmv.outputs.RELEASE_NEEDED == 'true' }}
    uses: ./.github/workflows/publish-notify.yml
    with:
      RELEASE_NEEDED: ${{ needs.release-nextmv.outputs.RELEASE_NEEDED == 'true' }}
      SHOULD_NOTIFY_SLACK: ${{ needs.release-nextmv.outputs.SHOULD_NOTIFY_SLACK }}
      VERSION: ${{ needs.release-nextmv.outputs.VERSION }}
      PACKAGE_NAME: nextmv
    secrets: inherit

  release-nextmv-gurobipy:
    uses: nextmv-io/release/.github/workflows/release.yml@develop
    with:
      BRANCH: ${{ github.ref_name }}
      REPOSITORY: nextmv-py
      LANGUAGE: python
      PACKAGE_NAME: nextmv_gurobipy
      PACKAGE_LOCATION: ./nextmv-gurobipy
      VERSION_FILE: __about__.py
    secrets: inherit

  publish-notify-nextmv-gurobipy:
    needs: [release-nextmv-gurobipy]
    if: ${{ needs.release-nextmv-gurobipy.outputs.RELEASE_NEEDED == 'true' }}
    uses: ./.github/workflows/publish-notify.yml
    with:
      RELEASE_NEEDED: ${{ needs.release-nextmv-gurobipy.outputs.RELEASE_NEEDED == 'true' }}
      SHOULD_NOTIFY_SLACK: ${{ needs.release-nextmv-gurobipy.outputs.SHOULD_NOTIFY_SLACK }}
      VERSION: ${{ needs.release-nextmv-gurobipy.outputs.VERSION }}
      PACKAGE_NAME: nextmv_gurobipy
    secrets: inherit

  release-nextmv-scikit-learn:
    uses: nextmv-io/release/.github/workflows/release.yml@develop
    with:
      BRANCH: ${{ github.ref_name }}
      REPOSITORY: nextmv-py
      LANGUAGE: python
      PACKAGE_NAME: nextmv_sklearn
      PACKAGE_LOCATION: ./nextmv-scikit-learn
      VERSION_FILE: __about__.py
    secrets: inherit

  publish-notify-nextmv-scikit-learn:
    needs: [release-nextmv-scikit-learn]
    if: ${{ needs.release-nextmv-scikit-learn.outputs.RELEASE_NEEDED == 'true' }}
    uses: ./.github/workflows/publish-notify.yml
    with:
      RELEASE_NEEDED: ${{ needs.release-nextmv-scikit-learn.outputs.RELEASE_NEEDED == 'true' }}
      SHOULD_NOTIFY_SLACK: ${{ needs.release-nextmv-scikit-learn.outputs.SHOULD_NOTIFY_SLACK }}
      VERSION: ${{ needs.release-nextmv-scikit-learn.outputs.VERSION }}
      PACKAGE_NAME: nextmv_sklearn
    secrets: inherit
