name: single binary build
on:
  push:
    branches: [develop]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
permissions:
  contents: read
jobs:
  single-binary-build:
    name: Single binary build for ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      # Keep this in line with the matrix in the release workflow to ensure tests are accurate
      matrix:
        include:
          - os: linux
            arch: x64
            runner: ubuntu-latest
            ext: ""
          - os: linux
            arch: arm64
            runner: ubuntu-24.04-arm
            ext: ""
          - os: macos
            arch: x64
            runner: macos-15-intel
            ext: ""
          - os: macos
            arch: arm64
            runner: macos-latest
            ext: ""
          - os: windows
            arch: x64
            runner: windows-latest
            ext: ".exe"

    steps:
      - name: checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: build and zip binary
        uses: ./.github/actions/build-binary
        with:
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}

      - name: smoketest binary
        env:
          NEXTMV_API_KEY: ${{ secrets.NEXTMV_API_KEY }}
          BINARY: ${{ matrix.os == 'windows' && './nextmv.exe' || './nextmv' }}
        run: |
          $BINARY --help
          $BINARY configuration create -a $NEXTMV_API_KEY
          $BINARY version
          $BINARY community clone -a python-highs-knapsack
          cd python-highs-knapsack
          # Use Python to run command with timeout since timeout is not available on macOS.
          # (Use a longer timeout due to Windows being slow to start the binary.)
          python -c "import subprocess; import os; subprocess.run(['.' + os.environ['BINARY'], 'local', 'run', 'create', '-i', 'input.json', '--wait'], timeout=60)"
        shell: bash
        working-directory: nextmv/dist/nextmv
