name: unit tests
on:
  push:
    branches: [develop]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
permissions:
  contents: read
jobs:
  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.13"]
        platform:
          [
            ubuntu-latest,
            ubuntu-24.04-arm,
            windows-latest,
            macos-latest,
            macos-15-intel,
          ]
        package: ["nextmv", "nextmv-gurobipy", "nextmv-scikit-learn"]
    steps:
      - name: git clone
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false

      - name: install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
        with:
          version: "0.9.29"
          python-version: ${{ matrix.python-version }}

      - name: install the project
        run: uv sync --locked --dev --all-extras
        working-directory: ./${{ matrix.package }}

      - name: handle nextmv dependency
        if: ${{ matrix.package != 'nextmv' }}
        run: |
          uv remove nextmv
          uv add --editable ../nextmv --no-sync
          uv sync --locked --dev --all-extras
        working-directory: ./${{ matrix.package }}

      - name: unit tests
        run: uv run pytest --ignore=tests/integration
        working-directory: ./${{ matrix.package }}
